# Generated by Django 4.1.3 on 2022-11-22 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=10, unique=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=50)])),
                ('price', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^[-,0-9]+€', 'Only numbers and commas allowed.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
