POST http://localhost:8000/signup/
Content-Type: application/json

{
  "username": "test8",
  "email": "test8@asd.com",
  "password": "test8"
}

###

POST http://localhost:8000/login/
Content-Type: application/json

{
  "username": "test8",
  "password": "test8"
}

###

POST http://localhost:8000/shop/
Authorization: Token b72c4249f321f71e9a1dfa362316d6203aef1158
Content-Type: application/json

{
  "title": "Mug",
  "description": "white",
  "price": 2
}
