
# FOR TESTING PURPOSES

POST http://localhost:8000/signup/
Content-Type: application/json

{
  "username": "test9",
  "email": "test9@asd.com",
  "password": "test9"
}

###

POST http://localhost:8000/api/login/
Content-Type: application/json

{
  "username": "test8",
  "password": "test8"
}

###

POST http://localhost:8000/api/cart/purchase/46/100
Authorization: Token b72c4249f321f71e9a1dfa362316d6203aef1158
Content-Type: application/json


###

GET http://localhost:8000/api/cart/
Authorization: Token 0627ccdc6fb21ad86844e8eb4a300b161af5237c
Content-Type: application/json

###

GET http://localhost:8000/api/listings/getprice/28
Content-Type: application/json

###

GET http://localhost:8000/api/myitems/sold/
Authorization: Token b72c4249f321f71e9a1dfa362316d6203aef1158
Content-Type: application/json

###

DELETE http://localhost:8000/api/cart/delete/
Authorization: Token 0627ccdc6fb21ad86844e8eb4a300b161af5237c
Content-Type: application/json

###
POST http://localhost:8000/api/cart/add/46
Authorization: Token b72c4249f321f71e9a1dfa362316d6203aef1158
Content-Type: application/json

###
DELETE http://localhost:8000/api/cart/remove/34
Authorization: Token 0627ccdc6fb21ad86844e8eb4a300b161af5237c
Content-Type: application/json

###

PUT http://localhost:8000/api/myitems/editlisting/47
Authorization: Token 0627ccdc6fb21ad86844e8eb4a300b161af5237c
Content-Type: application/json

{
  "title": "Drinkware",
  "description": "glass drinkware",
  "price": 15.0
}

###

POST http://localhost:8000/api/login/
Content-Type: application/json

{
  "username": "test8",
  "password": "test8"
}

###

POST http://localhost:8000/api/myitems/addlisting/
Authorization: Token b72c4249f321f71e9a1dfa362316d6203aef1158
Content-Type: application/json

{
  "title": "Ford fiesta",
  "description": "rusty",
  "price": 600
}

###

POST http://localhost:8000/myitems/addlisting/
Authorization: Token 5aca8ffdc761a906df40f3ee352a68403a659de0
Content-Type: application/json

{
  "title": "Volvo 740",
  "description": "Good condition",
  "price": 2500
}

###

PUT http://localhost:8000/myitems/editlisting/23
Authorization: Token 5aca8ffdc761a906df40f3ee352a68403a659de0
Content-Type: application/json

{
  "title": "Volvo 740",
  "description": "Good condition",
  "price": 1800
}

###

GET http://localhost:8000/myitems/
Authorization: Token 5aca8ffdc761a906df40f3ee352a68403a659de0

###

DELETE http://localhost:8000/myitems/deletelisting/22
Authorization: Token 5aca8ffdc761a906df40f3ee352a68403a659de0

###

GET http://localhost:8000/account/
Authorization: Token 13f2dddc6a421ae5a4b98ec540830bc8235171cd